# Generated by Django 3.1.5 on 2021-01-11 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20210111_1547'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='User',
        ),
    ]
